#!/usr/bin/env bash

set -e

if [ ! -f "/var/cache/stunnel-$STUNNEL_VERSION.tar.gz" ]; then
  wget -q --no-check-certificate -O /var/cache/stunnel-$STUNNEL_VERSION.tar.gz https://www.stunnel.org/downloads/stunnel-$STUNNEL_VERSION.tar.gz
  # cert is for mirt.net, which does not match stunnel.org
fi

tar zxf /var/cache/stunnel-$STUNNEL_VERSION.tar.gz

cd stunnel-$STUNNEL_VERSION
./configure --prefix=/app/vendor/stunnel
make
make install

cd /app/vendor/stunnel
tar -zcf - . | /gof3r put -b $S3_BUCKET -k stunnel-$STUNNEL_VERSION.tgz
